import {FOODATOI_CRITERIA,type Prospect,type Evidence} from './core.ts';
export const DEMO_ORG='demo-organization';
export const DEMO_PROJECT={id:'foodatoi-demo',organization_id:DEMO_ORG,name:'Foodatoi · Occitanie',offer:'Foodatoi propose votre carte en ligne et une interface comptoir pour les commandes à retirer, avec un abonnement fixe sans commission Foodatoi sur les ventes.',criteria:FOODATOI_CRITERIA};
function facts(source:string,items:[string,boolean,string][]):Evidence[]{return items.map(([criterion,value,excerpt],i)=>({id:`${source}-${i}`,criterion,value,excerpt,source_url:source,observed_at:'2026-09-16',status:'NOT_VERIFIED',verified_by:null}))}
export const DEMO_PROSPECTS:Prospect[]=[
 {id:'newschool',project_id:DEMO_PROJECT.id,organization_id:DEMO_ORG,name:'New School Tacos · Minimes',city:'Toulouse',website:'https://www.newschooltacos.fr/restaurants/toulouse-minimes',status:'À analyser',evidence:facts('https://www.newschooltacos.fr/restaurants/toulouse-minimes',[
 ['food',true,'La page officielle présente un restaurant de tacos.'],['region',true,'Adresse publiée : 110 boulevard Silvio Trentin, Toulouse.'],['phone_orders',true,'La page propose explicitement les commandes par téléphone.'],['platforms',true,'La page mentionne la livraison via Uber Eats.']]),channels:[{kind:'phone',value:'05 61 22 59 49',source_url:'https://www.newschooltacos.fr/restaurants/toulouse-minimes',verified:true}]},
 {id:'ofuzion',project_id:DEMO_PROJECT.id,organization_id:DEMO_ORG,name:'O’Fuzion',city:'Toulouse',website:'https://linktr.ee/ofuzion31',status:'À analyser',evidence:facts('https://linktr.ee/ofuzion31',[
 ['food',true,'Le profil présente une offre de restauration rapide.'],['region',true,'Adresse affichée : 3 rue Sirven, Toulouse.'],['platforms',true,'Le profil relie des pages de commande Uber Eats et Deliveroo.']]),channels:[{kind:'phone',value:'07 45 00 42 71',source_url:'https://linktr.ee/ofuzion31',verified:true}]},
 {id:'lombezienne',project_id:DEMO_PROJECT.id,organization_id:DEMO_ORG,name:'La Lombezienne',city:'Lombez',website:'https://www.lalombezienne.com/',status:'À analyser',evidence:facts('https://www.lalombezienne.com/',[
 ['food',true,'Le site officiel présente une pizzeria artisanale.'],['region',true,'Le site identifie une pizzeria à Lombez.'],['phone_orders',true,'Le parcours propose une commande par téléphone ou la préparation d’un SMS.']]),channels:[{kind:'phone',value:'05 62 06 94 69',source_url:'https://www.lalombezienne.com/',verified:true}]}
];
DEMO_PROSPECTS.push(
 {id:'pimpmyburger',project_id:DEMO_PROJECT.id,organization_id:DEMO_ORG,name:'Pimp My Burger',city:'Toulouse',website:'https://pimpmyburger.fr/',status:'À analyser',evidence:facts('https://pimpmyburger.fr/',[['food',true,'BURGERS'],['region',true,'54 avenue Jules Julien / 31400 Toulouse'],['platforms',true,'Livraison via Uber Eats & Deliveroo']]),channels:[]},
 {id:'bapz',project_id:DEMO_PROJECT.id,organization_id:DEMO_ORG,name:'Bapz',city:'Toulouse',website:'https://www.bapz.fr/',status:'À analyser',evidence:facts('https://www.bapz.fr/',[['food',true,'Nos pâtisseries à emporter ou à commander en ligne'],['region',true,'salon de thé à Toulouse']]),channels:[]}
);
export const DEMO_NOTES:Record<string,string>={pimpmyburger:'Une commande et un retrait sont proposés. Aucun déficit de click & collect établi.',bapz:'Commande en ligne et retrait sur place déjà annoncés : vérifier le besoin réel avant approche.',newschool:'Un lien de commande en ligne existe. Le fonctionnement du retrait et l’autonomie du franchisé restent à vérifier.',ofuzion:'Une solution directe Rushour est déjà liée. Cela ne prouve pas une livraison par une équipe interne. Audience et commandes sociales à confirmer.',lombezienne:'Un panier web et une préparation SMS existent. Ne pas présenter cet établissement comme dépourvu de solution numérique.'};
