import test from 'node:test';
import assert from 'node:assert/strict';
import {scoreProspect,generateOutreach,safeLink,csv,allowedAction} from '../src/domain/core.ts';
const criteria=[{key:'phone_orders',label:'Commandes par téléphone',weight:100}];
const now=new Date('2026-09-16T12:00:00Z');
const evidence={id:'1',criterion:'phone_orders',value:true,status:'VERIFIED',source_url:'https://example.com',excerpt:'Commandez par téléphone',observed_at:'2026-09-16',verified_by:'human'};
test('unknown never earns points',()=>assert.equal(scoreProspect(criteria,[],now).score,0));
test('verified earns weight',()=>assert.equal(scoreProspect(criteria,[evidence],now).score,100));
test('false is known without points',()=>{const s=scoreProspect(criteria,[{...evidence,value:false}],now);assert.equal(s.score,0);assert.equal(s.coverage,100)});
test('inference not promoted',()=>assert.equal(scoreProspect(criteria,[{...evidence,status:'INFERRED_UNCONFIRMED'}],now).score,0));
test('missing reviewer never verified',()=>assert.equal(scoreProspect(criteria,[{...evidence,verified_by:null}],now).score,0));
test('stale and future evidence ignored',()=>{for(const date of ['2020-01-01','2027-01-01'])assert.equal(scoreProspect(criteria,[{...evidence,observed_at:date}],now).score,0)});
test('duplicates counted once',()=>assert.equal(scoreProspect(criteria,[evidence,evidence],now).score,100));
test('conflicting observations need review',()=>{const s=scoreProspect(criteria,[evidence,{...evidence,id:'2',value:false}],now);assert.equal(s.score,0);assert.equal(s.breakdown[0].state,'CONFLICT')});
test('unknown DM does not invent phone orders',()=>assert.doesNotMatch(generateOutreach('Test','Foodatoi',criteria,[],now).text,/vous prenez|vous proposez|par téléphone/));
test('verified DM cites evidence ids',()=>assert.deepEqual(generateOutreach('Test','Foodatoi',criteria,[evidence],now).evidence_ids,['1']));
test('dangerous links rejected',()=>{for(const u of ['javascript:alert(1)','data:text/html,x','https://user:pass@example.com'])assert.equal(safeLink(u),null)});
test('CSV prevents formulas and escapes quotes',()=>assert.match(csv([['=1+1','a"b']]),/"'=1\+1","a""b"/));
test('LinkedIn final actions are human',()=>{assert.equal(allowedAction('linkedin_send'),false);assert.equal(allowedAction('mark_contacted'),true)});
