import {z} from 'zod';
const publicUrl=z.string().max(2048).url().refine(v=>{const u=new URL(v);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password},'HTTP(S) requis');
// Generic contract: PROJECT -> OFFER -> ICP -> QUERY. offer/criteria are optional context carried
// alongside the search terms (persisted as-is in discovery_runs.filters_json) — never a hidden
// fallback: when omitted, the query stays exactly what the user typed, with no vertical injected.
const CriterionContextSchema=z.object({key:z.string().min(1).max(60),label:z.string().min(1).max(120),weight:z.number()}).strict();
export const DiscoveryInputSchema=z.object({project_id:z.string().min(1).max(100),query:z.string().trim().min(2).max(250),location:z.string().trim().min(2).max(120),categories:z.array(z.string().trim().min(1).max(60)).max(12),max_results:z.number().int().min(1).max(100).default(20),optional_filters:z.object({provider:z.enum(['fixture','brave']).optional(),country:z.string().regex(/^[A-Z]{2}$/).optional(),offer:z.string().max(4000).optional(),criteria:z.array(CriterionContextSchema).max(30).optional()}).strict().default({})}).strict();
export type DiscoveryInput=z.infer<typeof DiscoveryInputSchema>;
export const CandidateSchema=z.object({name:z.string().min(1).max(200),canonical_url:publicUrl.nullable(),website:publicUrl.nullable(),city:z.string().max(120).nullable(),address:z.string().max(400).nullable(),phone:z.string().max(60).nullable(),discovered_source:z.string().max(80),source_url:publicUrl,source_title:z.string().max(300),discovery_timestamp:z.string().datetime(),confidence:z.number().min(0).max(1),raw_metadata:z.record(z.string(),z.unknown()),deduplication_key:z.string().max(1000)}).strict();
export type Candidate=z.infer<typeof CandidateSchema>;
export interface DiscoveryProvider {id:string;mode:'live'|'test';searchCompanies(input:DiscoveryInput):Promise<unknown[]>;fetchCompanyDetails(candidate:Candidate):Promise<Candidate>;normalizeResult(raw:unknown):Candidate}
// criterion is validated against the project's own ICP at proposal time (EvidenceProposalService,
// save_discovery_observations) — never against a fixed vertical's key list, so any ICP works here.
export const ObservationSchema=z.object({criterion:z.string().min(1).max(60).nullable(),observation_type:z.string().min(1).max(60),claim:z.string().max(1000),value:z.boolean().nullable(),status:z.enum(['OBSERVED','UNKNOWN','INFERRED','CONTRADICTED']),source_url:publicUrl,source_title:z.string().max(300),source_excerpt:z.string().max(500),source_type:z.enum(['official_website','search_result','public_directory','test_fixture']),confidence:z.number().min(0).max(1),collected_at:z.string().datetime(),expires_at:z.string().datetime(),content_hash:z.string().min(1).max(100)}).strict().superRefine((v,c)=>{if(v.status!=='UNKNOWN'&&!v.source_excerpt.trim())c.addIssue({code:'custom',message:'Extrait requis'});if(v.status==='UNKNOWN'&&v.value!==null)c.addIssue({code:'custom',message:'UNKNOWN doit avoir value=null'})});
export type Observation=z.infer<typeof ObservationSchema>;
export type StoredObservation=Observation&{id:string;prospect_id:string;organization_id:string;evidence_id:string|null;review_status:'NOT_VERIFIED'|'VERIFIED'|'CONTRADICTED'};
export type DiscoveryResult={id:string;normalized_payload:Candidate;dedupe_status:'unique'|'duplicate_candidate'|'merge_review_required';duplicate_of:string|null;status:'pending'|'accepted'|'ignored';prospect_id:string|null;reason?:string};
export type DiscoveryRun={id:string;status:string;provider:string;result_count:number;error_message:string|null;results?:DiscoveryResult[]};
