'use client';
import {useEffect,useRef,useState} from 'react';
import snapshots from '../discovery/demo-observations.json';
import type {StoredObservation,Observation} from '../discovery/types';
import type {Evidence,Prospect} from '../domain/core';
import {translate,observationBadgeLabel,observationMeta,type Locale,type TKey} from '../i18n';
type Api=(path:string,method?:string,body?:unknown)=>Promise<any>;
export function ObservationsReview({prospect,mode,api,onChanged,disabled,onBusyChange,locale}:{prospect:Prospect;mode:'demo'|'live';api:Api;disabled:boolean;onBusyChange:(active:boolean)=>void;onChanged:(evidence?:Evidence[])=>Promise<void>;locale:Locale}){
 const tr=(key:TKey)=>translate(locale,key);
 const [rows,setRows]=useState<StoredObservation[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[website,setWebsite]=useState(prospect.website??'');const generation=useRef(0);
 const key=`prospectos-observations:${prospect.id}`;
 useEffect(()=>{const r=++generation.current;setRows([]);setWebsite(prospect.website??'');setError('');if(mode==='demo'){try{setRows(JSON.parse(localStorage.getItem(key)??'[]'))}catch{}}else api(`prospects/${prospect.id}/observations`).then(data=>{if(r===generation.current)setRows(data)}).catch(()=>{if(r===generation.current)setError(tr('evidence.unavailable'))});return()=>{generation.current++}},[prospect.id,mode]);
 const persist=(next:StoredObservation[])=>{setRows(next);if(mode==='demo')localStorage.setItem(key,JSON.stringify(next))};
 async function execute(fn:()=>Promise<void>){if(disabled||busy)return;onBusyChange(true);setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:tr('error.generic'))}finally{setBusy(false);onBusyChange(false)}}
 function evidenceFor(o:StoredObservation):Evidence|null{if(!o.evidence_id||!o.criterion||o.value===null)return null;return {id:o.evidence_id,criterion:o.criterion,value:o.value,status:o.review_status,source_url:o.source_url,excerpt:o.source_excerpt,observed_at:o.collected_at,verified_by:o.review_status==='NOT_VERIFIED'?null:'demo-human'}}
 async function analyze(){await execute(async()=>{const r=generation.current;if(mode==='demo'){
 if(localStorage.getItem(`prospectos-discovery-origin:${prospect.id}`)!=='fixture')throw Error(tr('evidence.demoAnalyzeRestriction'));
 const collected=new Date(),expires=new Date(+collected+90*86400000);const next=snapshots.map(raw=>{const old=rows.find(o=>o.observation_type===raw.observation_type);return old??{...raw,id:crypto.randomUUID(),prospect_id:prospect.id,organization_id:prospect.organization_id,source_url:prospect.website,collected_at:collected.toISOString(),expires_at:expires.toISOString(),evidence_id:raw.criterion&&raw.status!=='UNKNOWN'?crypto.randomUUID():null,review_status:'NOT_VERIFIED'}}) as StoredObservation[];if(r!==generation.current)return;persist(next);await onChanged(next.map(evidenceFor).filter((e):e is Evidence=>!!e));
 }else {const result=await api(`prospects/${prospect.id}/analyze`,'POST',{});if(r!==generation.current)return;setRows(result.observations);await onChanged()}})}
 async function review(row:StoredObservation,decision:'confirm'|'contradict'|'unverify'){await execute(async()=>{const r=generation.current;const changed=mode==='demo'?{...row,review_status:decision==='confirm'?'VERIFIED':decision==='contradict'?'CONTRADICTED':'NOT_VERIFIED'}:await api(`prospects/${prospect.id}/observations/${row.id}/${decision}`,'POST',{});if(r!==generation.current)return;persist(rows.map(o=>o.id===row.id?changed:o));const evidence=evidenceFor(changed);await onChanged(mode==='demo'&&evidence?[evidence]:undefined)})}
 return <section className="observations-review"><div className="section-title"><h3>{tr('evidence.reviewTitle')}</h3><button disabled={busy||disabled} onClick={analyze}>{tr('evidence.analyzeWebsite')}</button></div><p className="muted">{tr('evidence.foundVsVerified')}</p>{!prospect.website&&mode==='live'&&<form onSubmit={e=>{e.preventDefault();execute(async()=>{await api(`prospects/${prospect.id}/website`,'POST',{website,official_confirmed:true});await onChanged()})}}><label>{tr('evidence.officialWebsiteLabel')}<input type="url" required value={website} onChange={e=>setWebsite(e.target.value)}/></label><label className="checkbox"><input type="checkbox" required/>{tr('evidence.confirmWebsiteCheckbox')}</label><button disabled={busy||disabled}>{tr('evidence.saveWebsite')}</button></form>}{error&&<p role="alert" className="note">{error}</p>}<div className="observations">{rows.map(o=><details key={o.id}><summary><span>{o.observation_type}</span><span className="pill">{observationBadgeLabel(o.review_status,o.status,locale)}</span></summary><p>{o.claim}</p>{o.source_excerpt&&<blockquote>{o.source_excerpt}</blockquote>}<a href={o.source_url} target="_blank" rel="noreferrer">{o.source_title} ↗</a><p className="muted">{observationMeta(locale,o.source_type,o.collected_at,Math.round(o.confidence*100),o.expires_at)}</p>{o.evidence_id&&<div className="actions"><button disabled={busy||disabled} onClick={()=>review(o,'confirm')}>{tr('evidence.confirmAfterReading')}</button><button disabled={busy||disabled} onClick={()=>review(o,'contradict')}>{tr('evidence.contradict')}</button><button disabled={busy||disabled} onClick={()=>review(o,'unverify')}>{tr('evidence.leaveUnverified')}</button></div>}{!o.evidence_id&&<p className="muted">{tr('evidence.noPositiveEvidence')}</p>}</details>)}</div></section>
}
